export const GeneralSentences = [
    { "emoji": "🔥❓", "bedeutung": "Habe ich den Herd ausgemacht?" },
    { "emoji": "💧➡️🥤", "bedeutung": "Ich sollte mehr Wasser trinken." },
    { "emoji": "🤔🍝🍱🍔", "bedeutung": "Was esse ich heute zum Mittag?" },
    { "emoji": "⏰🤨", "bedeutung": "Wie spät ist es eigentlich schon?" },
    { "emoji": "📱💬🤷‍♂️", "bedeutung": "Warum schreibt sie/er mir nicht zurück?" },
    { "emoji": "📝🗒️✅", "bedeutung": "Ich sollte das wirklich auf meine To-do-Liste schreiben." },
    { "emoji": "😌🕔🏠", "bedeutung": "Ich freue mich schon auf Feierabend." },
    { "emoji": "🙄🕰️💼", "bedeutung": "Hoffentlich wird das Meeting nicht zu lange dauern." },
    { "emoji": "🤔👤❓", "bedeutung": "Woher kenne ich diese Person nochmal?" },
    { "emoji": "😒🧹🧼", "bedeutung": "Ich habe keine Lust, aufzuräumen." },
    { "emoji": "🛏️🕰️😩", "bedeutung": "Wäre ich doch heute länger im Bett geblieben." },
    { "emoji": "🏃‍♀️💪🤔", "bedeutung": "Ich sollte mehr Sport machen." },
    { "emoji": "😬🔑❓", "bedeutung": "Mist, wo habe ich meinen Schlüssel hingelegt?" },
    { "emoji": "☕🤔😋", "bedeutung": "Vielleicht gönne ich mir später noch einen Kaffee." },
    { "emoji": "📧✅❓", "bedeutung": "Habe ich diese E-Mail schon beantwortet?" },
    { "emoji": "🚗🚦😠", "bedeutung": "Warum ist der Verkehr heute so schlimm?" },
    { "emoji": "💡📝🔜", "bedeutung": "Das sollte ich mir für später merken." },
    { "emoji": "😰🤯❗", "bedeutung": "Ich hoffe, ich habe nichts Wichtiges vergessen." },
    { "emoji": "🥱😴🤔", "bedeutung": "Ob die anderen auch so müde sind wie ich?" },
    { "emoji": "📺🍿❓", "bedeutung": "Was soll ich heute Abend schauen?" },
    { "emoji": "⏳✅🤔", "bedeutung": "Habe ich genug Zeit für alles eingeplant?" },
    { "emoji": "🌴📅🗓️", "bedeutung": "Wann ist nochmal der nächste Urlaub?" },
    { "emoji": "☀️🌧️🤔", "bedeutung": "Das Wetter ist heute echt schön/schlecht." },
    { "emoji": "🤯🤹‍♂️🔥", "bedeutung": "Wie schafft es diese Person, so produktiv zu sein?" },
    { "emoji": "📱👨‍👩‍👧‍👦📞", "bedeutung": "Ich sollte bald mal wieder meine Eltern/Freunde anrufen." },
    { "emoji": "😤🙋‍♀️❓", "bedeutung": "Warum muss immer ich das machen?" },
    { "emoji": "🎨🎸🏃‍♂️⌛", "bedeutung": "Ich wünschte, ich hätte mehr Zeit für meine Hobbys." },
    { "emoji": "💸🗓️🤔", "bedeutung": "Habe ich genug Geld für den Monat übrig?" },
    { "emoji": "😊💭🔜", "bedeutung": "Ich sollte positiver denken." },
    { "emoji": "😩🛏️🍀", "bedeutung": "Heute ist einfach nicht mein Tag." },
    { "emoji": "🤔🗑️🗓️", "bedeutung": "Wann wird der Müll abgeholt?" },
    { "emoji": "🍫😋❓", "bedeutung": "Habe ich noch Schokolade zuhause?" },
    { "emoji": "📆✍️🤔", "bedeutung": "Habe ich heute einen wichtigen Termin?" },
    { "emoji": "🛒🤔📋", "bedeutung": "Habe ich alles auf meiner Einkaufsliste?" },
    { "emoji": "📚📖🤔", "bedeutung": "Welches Buch soll ich als nächstes lesen?" },
    { "emoji": "🔋⚡❓", "bedeutung": "Habe ich mein Handy aufgeladen?" },
    { "emoji": "🛑🤚🚶", "bedeutung": "Sollte ich hier lieber anhalten?" },
    { "emoji": "🖼️🛠️🤔", "bedeutung": "Sollte ich diese Wand dekorieren?" },
    { "emoji": "🎂🎉🎁", "bedeutung": "Habe ich an den Geburtstag von XY gedacht?" },
    { "emoji": "🏡🔨💭", "bedeutung": "Sollte ich dieses Wochenende renovieren?" },
    { "emoji": "💼📈🤔", "bedeutung": "Bin ich für das Meeting gut vorbereitet?" },
    { "emoji": "🍕🍴😋", "bedeutung": "Ob ich mir Pizza bestellen soll?" },
    { "emoji": "🚴‍♀️🌳☀️", "bedeutung": "Das Wetter ist perfekt für eine Radtour." },
    { "emoji": "🖥️⌨️😑", "bedeutung": "Warum lädt dieser Computer so lange?" },
    { "emoji": "💭📊🚀", "bedeutung": "Wie könnte ich mich beruflich verbessern?" },
    { "emoji": "💵💳❓", "bedeutung": "Habe ich genug Bargeld dabei?" },
    { "emoji": "🎶🎧🕺", "bedeutung": "Ich sollte wieder mehr Musik hören." },
    { "emoji": "👗👞🤔", "bedeutung": "Was ziehe ich heute an?" },
    { "emoji": "🍎🍌🥗", "bedeutung": "Ich sollte heute gesünder essen." },
    { "emoji": "💻💾📂", "bedeutung": "Habe ich meine Dateien gesichert?" },
    { "emoji": "👨‍💻🕔😵", "bedeutung": "Wie ist der Arbeitstag so schnell vergangen?" },
    { "emoji": "🐾🦴🤔", "bedeutung": "Hat mein Haustier genug Futter?" },
    { "emoji": "📦🛍️✂️", "bedeutung": "Habe ich noch alles für mein DIY-Projekt?" },
    { "emoji": "🚦🛑🤔", "bedeutung": "Wie lange bleibt diese Ampel noch rot?" },
    { "emoji": "🚌🕒😟", "bedeutung": "Komme ich noch rechtzeitig zur Haltestelle?" },
    { "emoji": "👤👥🚶", "bedeutung": "Warum läuft diese Person so langsam vor mir?" },
    { "emoji": "☔🧥🤔", "bedeutung": "Hätte ich heute einen Regenschirm mitnehmen sollen?" },
    { "emoji": "🍞🥛🛒", "bedeutung": "Sollte ich schnell noch im Supermarkt vorbeigehen?" },
    { "emoji": "🚶‍♀️🕒💨", "bedeutung": "Sollte ich schneller laufen, um Zeit zu sparen?" },
    { "emoji": "📱🎧🎵", "bedeutung": "Welche Playlist passt gerade zu meiner Stimmung?" },
    { "emoji": "🏙️🌆😌", "bedeutung": "Die Stadt sieht heute irgendwie schön aus." },
    { "emoji": "🤔📍🚶", "bedeutung": "Wo war nochmal der kürzeste Weg dahin?" },
    { "emoji": "🍽️🥤❓", "bedeutung": "Ob ich mir unterwegs einen Snack holen soll?" },
    { "emoji": "🚕💭🤑", "bedeutung": "Sollte ich ein Taxi nehmen, um schneller anzukommen?" },
    { "emoji": "👕💦😖", "bedeutung": "Warum ist es heute so warm? Ich schwitze total." },
    { "emoji": "🐦🌳👀", "bedeutung": "Schau mal, wie viele Vögel heute unterwegs sind!" },
    { "emoji": "🤳🏙️📸", "bedeutung": "Sollte ich ein Foto von dieser Aussicht machen?" },
    { "emoji": "🚴‍♂️🚶‍♀️🤯", "bedeutung": "Fast hätte mich der Radfahrer umgefahren!" },
    { "emoji": "📱💬🕰️", "bedeutung": "Sollte ich mich beeilen und kurz absagen?" },
    { "emoji": "🌮🌯🤤", "bedeutung": "Es riecht hier so gut! Woher kommt das?" },
    { "emoji": "🚗🚙🚦😠", "bedeutung": "Warum hupen hier alle ständig?" },
    { "emoji": "💼🚇😑", "bedeutung": "Bitte lass den nächsten Zug nicht zu voll sein." },
    { "emoji": "📖👓🚌", "bedeutung": "Kann ich wohl im Bus ein Buch lesen?" },
    { "emoji": "🌍🌱🤔", "bedeutung": "Ich sollte öfter zu Fuß gehen, das ist besser für die Umwelt." },
    { "emoji": "🧑‍⚕️🕒😰", "bedeutung": "Wie lange werde ich beim Arzt warten müssen?" },
    { "emoji": "🤔📅💉", "bedeutung": "War mein Termin heute um 14:30 oder 15:00 Uhr?" },
    { "emoji": "🎒📚🏫", "bedeutung": "Habe ich wirklich alles für die Schule eingepackt?" },
    { "emoji": "🚶🍂🏙️", "bedeutung": "Der Herbst fühlt sich heute echt gemütlich an." },
    { "emoji": "🛑🛤️🤔", "bedeutung": "Soll ich an den Gleisen warten oder den Umweg nehmen?" },
    { "emoji": "📱🌐❓", "bedeutung": "Habe ich hier überhaupt Empfang?" },
    { "emoji": "🚴💨😲", "bedeutung": "Wie fährt dieser Radfahrer nur so schnell?" },
    { "emoji": "🚶‍♂️💭🛍️", "bedeutung": "Vielleicht sollte ich später noch einkaufen gehen." },
    { "emoji": "💇💭✂️", "bedeutung": "Wann war ich eigentlich das letzte Mal beim Friseur?" },
    { "emoji": "😅🌧️🕶️", "bedeutung": "Ich hätte definitiv eine Jacke gebraucht." },
    { "emoji": "🏃‍♀️📅⏰", "bedeutung": "Bin ich schon wieder zu spät dran?" },
    { "emoji": "🧑‍💻📧🤔", "bedeutung": "Sollte ich jetzt noch die E-Mails checken?" },
    { "emoji": "📞🤔📅", "bedeutung": "Habe ich heute noch einen wichtigen Anruf vergessen?" },
    { "emoji": "🍩☕🥤", "bedeutung": "Vielleicht hole ich mir noch einen Donut und Kaffee." },
    { "emoji": "🚶‍♀️👖🪞", "bedeutung": "Ob meine Hose heute richtig sitzt?" },
    { "emoji": "🐕🐾💩", "bedeutung": "Hoffentlich räumt die Person den Hundehaufen weg." },
    { "emoji": "🛑🕒🚲", "bedeutung": "Warum hält niemand an der roten Ampel?" },
    { "emoji": "📍🗺️🤔", "bedeutung": "Ob ich wirklich in die richtige Richtung laufe?" },
    { "emoji": "👜💭🗝️", "bedeutung": "Habe ich meinen Schlüssel eingepackt?" },
    { "emoji": "🎧🔋❓", "bedeutung": "Hoffentlich reicht der Akku meiner Kopfhörer." },
    { "emoji": "🚶‍♀️👗👜", "bedeutung": "Woher hat sie wohl dieses Kleid?" },
    { "emoji": "🥶🧤❓", "bedeutung": "Warum habe ich keine Handschuhe dabei?" },
    { "emoji": "🚶🌳🌸", "bedeutung": "Diese Bäume riechen heute echt gut." },
    { "emoji": "😤🚶‍♂️🛑", "bedeutung": "Warum bleibt diese Person plötzlich stehen?" },
    { "emoji": "🚇🕒📱", "bedeutung": "Wie lange dauert der nächste Zug?" },
    { "emoji": "🏙️🚁👀", "bedeutung": "Ob das ein Polizei-Helikopter ist?" },
    { "emoji": "💼👟❓", "bedeutung": "Ich hätte wohl bequemere Schuhe anziehen sollen." },
    { "emoji": "🌦️🌂😅", "bedeutung": "Zum Glück habe ich doch einen Schirm mitgenommen." },
    { "emoji": "📱🧑‍🤝‍🧑💬", "bedeutung": "Sollte ich XY fragen, ob sie auch kommen?" },
    { "emoji": "🏪🍫🤔", "bedeutung": "Ich sollte mir später einen Snack holen." },
    { "emoji": "😋🍔🚶", "bedeutung": "Dieser Burger-Laden riecht so gut!" },
    { "emoji": "🚗🚧🙄", "bedeutung": "Immer diese Baustellen überall!" },
    { "emoji": "🚶🌊🍃", "bedeutung": "Ich liebe es, den Wind zu spüren." },
    { "emoji": "🐕👀🐾", "bedeutung": "Schau mal, wie süß dieser Hund ist!" },
    { "emoji": "📆🚶🤷‍♀️", "bedeutung": "Ob ich heute noch etwas vergessen habe?" },
    { "emoji": "🌭🤤", "bedeutung": "Das sieht lecker aus, soll ich mir einen Hotdog holen?" },
    { "emoji": "🍟😋", "bedeutung": "Die Pommes riechen fantastisch!" },
    { "emoji": "🍔🤔", "bedeutung": "Ob ich hier den besten Burger der Stadt bekomme?" },
    { "emoji": "🌯💭", "bedeutung": "Lust auf einen Burrito?" },
    { "emoji": "🍕👀", "bedeutung": "Ist das eine Pizza? Wie groß sieht die aus!" },
    { "emoji": "🥤🥵", "bedeutung": "Ich könnte einen kühlen Softdrink vertragen." },
    { "emoji": "🍗🤤", "bedeutung": "Die Chicken Wings sehen knusprig aus." },
    { "emoji": "🧄🫓", "bedeutung": "Soll ich mir einen Döner gönnen?" },
    { "emoji": "🍤🤔", "bedeutung": "Haben die hier auch etwas Vegetarisches oder Veganes?" },
    { "emoji": "🌮😋", "bedeutung": "Wie wäre es mit einem Taco?" },
    { "emoji": "💵💭", "bedeutung": "Habe ich genug Bargeld dabei?" },
    { "emoji": "⌛😒", "bedeutung": "Die Schlange ist aber lang." },
    { "emoji": "👃🍴", "bedeutung": "Es riecht so gut, ich werde schwach!" },
    { "emoji": "🍦🤩", "bedeutung": "Die haben auch Eiscreme, wie cool!" },
    { "emoji": "🥙😋", "bedeutung": "Der Wrap sieht richtig frisch aus." },
    { "emoji": "🐟🍋", "bedeutung": "Sollte ich Fisch und Chips probieren?" },
    { "emoji": "🍫🥤", "bedeutung": "Haben die auch Desserts?" },
    { "emoji": "🍔💸", "bedeutung": "Wie teuer ist ein Menü hier?" },
    { "emoji": "👨‍🍳🔥", "bedeutung": "Die kochen das alles frisch – das mag ich!" },
    { "emoji": "🚶🤔", "bedeutung": "Soll ich kurz anhalten oder lieber weitergehen?" },
    { "emoji": "😓🌭", "bedeutung": "Bin ich hungrig genug, oder wäre das übertrieben?" },
    { "emoji": "👀📜", "bedeutung": "Was steht auf der Speisekarte?" },
    { "emoji": "🍗🔥🤤", "bedeutung": "Die gegrillten Sachen duften fantastisch." },
    { "emoji": "🛑🍴", "bedeutung": "Das muss ich ausprobieren, ich bleibe hier stehen!" },
    { "emoji": "🍔👨‍👩‍👧‍👦", "bedeutung": "Ob das ein guter Ort ist, um mit Freunden herzukommen?" },
    { "emoji": "🍟😔", "bedeutung": "Schade, dass ich gerade keinen Hunger habe." },
    { "emoji": "🧺🚶", "bedeutung": "Vielleicht hole ich mir etwas zum Mitnehmen?" },
    { "emoji": "🌯🌶️", "bedeutung": "Ob der Burrito hier scharf ist?" },
    { "emoji": "🤤🍳", "bedeutung": "Die braten das direkt vor deinen Augen!" },
    { "emoji": "🍕🏆", "bedeutung": "Vielleicht gibt es hier die beste Pizza der Gegend." },
    { "emoji": "🍤🥢", "bedeutung": "Ob sie asiatische Snacks im Angebot haben?" },
    { "emoji": "🥩🧂", "bedeutung": "Das Steak riecht verdammt gut." },
    { "emoji": "🥗🍴", "bedeutung": "Haben sie auch Salate? Vielleicht mal etwas Gesundes." },
    { "emoji": "🕐🍴", "bedeutung": "Habe ich genug Zeit, um hier kurz zu essen?" },
    { "emoji": "🍳🥓", "bedeutung": "Die Speckbrötchen sehen knusprig aus." },
    { "emoji": "🚴‍♀️🍔", "bedeutung": "Vielleicht stoppe ich hier auf dem Rückweg." },
    { "emoji": "🍤❓", "bedeutung": "Ist das da Tempura?" },
    { "emoji": "🍡😋", "bedeutung": "Die haben Spieße! Vielleicht probiere ich die." },
    { "emoji": "🍹☀️", "bedeutung": "Ein kühler Cocktail würde jetzt perfekt passen." },
    { "emoji": "😋🌮", "bedeutung": "Wie wäre es mit einem Taco als Snack?" },
    { "emoji": "👨‍🍳🍔", "bedeutung": "Ich wette, das ist ein Familienbetrieb." },
    { "emoji": "🍔🧀", "bedeutung": "Haben sie auch Cheeseburger?" },
    { "emoji": "🥤🤨", "bedeutung": "Ob die Getränke hier überteuert sind?" },
    { "emoji": "🌭💭", "bedeutung": "Wie wäre es mit einem Snack für unterwegs?" },
    { "emoji": "🌱🌯", "bedeutung": "Haben die etwas Veganes im Angebot?" },
    { "emoji": "🍗🥵", "bedeutung": "Hoffentlich sind die Sachen nicht zu scharf." },
    { "emoji": "🍛🤔", "bedeutung": "Ob sie hier auch Curry haben?" },
    { "emoji": "💳🍴", "bedeutung": "Hoffentlich kann ich mit Karte zahlen." },
    { "emoji": "🍔👩‍🍳", "bedeutung": "Ob der Chefkoch freundlich ist?" },
    { "emoji": "🍟🛒", "bedeutung": "Soll ich noch ein paar Pommes mitnehmen?" },
    { "emoji": "🚶🍔", "bedeutung": "Vielleicht sollte ich später zurückkommen." },
    { "emoji": "🍦🤔", "bedeutung": "Ich habe Lust auf ein Dessert danach." },
    { "emoji": "🍗🥙", "bedeutung": "Ein Wrap wäre eine gute Wahl." },
    { "emoji": "🥘🤤", "bedeutung": "Der Eintopf sieht so einladend aus!" },
    { "emoji": "🥡🍜", "bedeutung": "Vielleicht nehme ich etwas für zuhause mit." },
    { "emoji": "🍔👀", "bedeutung": "Die Portionen sehen riesig aus." },
    { "emoji": "🤤🍩", "bedeutung": "Die haben Donuts! Das wäre ein süßer Abschluss." },
    { "emoji": "🍤🚶", "bedeutung": "Ich sollte wenigstens einmal probieren!" },
    { "emoji": "🍳🍅", "bedeutung": "Ob sie hier ein Frühstücksmenü anbieten?" },
    { "emoji": "🍔🍗🤔", "bedeutung": "Kann ich mich zwischen einem Burger und Chicken Wings entscheiden?" },
    { "emoji": "🍴🧽", "bedeutung": "Wie sauber ist wohl die Küche hier?" },
    { "emoji": "🍔🍷", "bedeutung": "Ob sie auch Getränke mit Alkohol anbieten?" },
    { "emoji": "🍟📸", "bedeutung": "Die sehen so gut aus, dass ich ein Foto machen könnte!" },
    { "emoji": "👥🍔", "bedeutung": "Warum gibt es hier so eine große Schlange?" },
    { "emoji": "⌛🚶", "bedeutung": "Hoffentlich komme ich pünktlich an." },
    { "emoji": "📱💬", "bedeutung": "Sollte ich schreiben, dass ich gleich da bin?" },
    { "emoji": "👕👖🤔", "bedeutung": "Habe ich das richtige Outfit gewählt?" },
    { "emoji": "🪞💭", "bedeutung": "Wie sehe ich gerade aus? Alles noch in Ordnung?" },
    { "emoji": "💐🤔", "bedeutung": "Hätte ich Blumen mitbringen sollen?" },
    { "emoji": "💭😅", "bedeutung": "Hoffentlich mag er/sie mich wirklich." },
    { "emoji": "📱🎧", "bedeutung": "Welche Musik passt zu meiner Stimmung jetzt?" },
    { "emoji": "🍫❓", "bedeutung": "Ob ich unterwegs noch etwas Süßes besorge?" },
    { "emoji": "🤔📍", "bedeutung": "Bin ich sicher, dass ich die richtige Richtung laufe?" },
    { "emoji": "🚶‍♀️💨", "bedeutung": "Vielleicht sollte ich schneller gehen." },
    { "emoji": "💭💋", "bedeutung": "Was, wenn es heute zu einem Kuss kommt?" },
    { "emoji": "😅🤝", "bedeutung": "Wie begrüße ich sie/ihn? Mit einer Umarmung?" },
    { "emoji": "💬😬", "bedeutung": "Hoffentlich habe ich genug Gesprächsthemen vorbereitet." },
    { "emoji": "🌸🌳", "bedeutung": "Was für ein schöner Tag für ein Treffen!" },
    { "emoji": "📱📅", "bedeutung": "Ist es wirklich heute? Ich hoffe, ich habe nichts verwechselt." },
    { "emoji": "🤔🍴", "bedeutung": "Wo gehen wir essen? Hoffentlich ist es ein cooler Ort." },
    { "emoji": "💨🍃", "bedeutung": "Hoffentlich schwitze ich nicht zu sehr auf dem Weg." },
    { "emoji": "👞🤨", "bedeutung": "Sind meine Schuhe sauber genug?" },
    { "emoji": "👃😅", "bedeutung": "Hoffentlich rieche ich frisch." },
    { "emoji": "😩🏃", "bedeutung": "Warum bin ich so nervös?!" },
    { "emoji": "🕒🚶", "bedeutung": "Bin ich zu früh oder zu spät losgegangen?" },
    { "emoji": "🍦❓", "bedeutung": "Vielleicht lade ich sie/ihn auf ein Eis ein." },
    { "emoji": "💄💭", "bedeutung": "Sitzt mein Lippenstift noch richtig?" },
    { "emoji": "🤔👗", "bedeutung": "War das zu schick oder zu leger?" },
    { "emoji": "🌂☁️", "bedeutung": "Was, wenn es gleich anfängt zu regnen?" },
    { "emoji": "🤗🍀", "bedeutung": "Ich hoffe, wir haben eine richtig gute Zeit zusammen." },
    { "emoji": "💬😂", "bedeutung": "Hoffentlich bringe ich sie/ihn zum Lachen." },
    { "emoji": "🚶👥", "bedeutung": "Ich hoffe, ich erkenne sie/ihn sofort." },
    { "emoji": "🤯😱", "bedeutung": "Was, wenn ich etwas komplett Dummes sage?" },
    { "emoji": "🛑🌹", "bedeutung": "Vielleicht kaufe ich spontan noch eine Blume?" },
    { "emoji": "🍹🥂", "bedeutung": "Trinken wir heute etwas zusammen?" },
    { "emoji": "🍔🤔", "bedeutung": "Hoffentlich mag sie/er dasselbe Essen wie ich." },
    { "emoji": "🧴💭", "bedeutung": "Hätte ich mehr Parfüm benutzen sollen?" },
    { "emoji": "😳👋", "bedeutung": "Was, wenn ich mich unbeholfen begrüße?" },
    { "emoji": "🤔🎥", "bedeutung": "Vielleicht schlage ich vor, ins Kino zu gehen." },
    { "emoji": "🎶🚶", "bedeutung": "Diese Musik macht mich entspannt für das Treffen." },
    { "emoji": "🌆✨", "bedeutung": "Es ist wirklich die perfekte Zeit für ein Treffen." },
    { "emoji": "🗣️🤨", "bedeutung": "Hoffentlich wird es kein unangenehmes Schweigen geben." },
    { "emoji": "🍷💬", "bedeutung": "Vielleicht sprechen wir über unsere Lieblingsfilme." },
    { "emoji": "😌🌿", "bedeutung": "Ich sollte tief durchatmen, um ruhig zu bleiben." },
    { "emoji": "📱😟", "bedeutung": "Hoffentlich sagt sie/er nicht kurzfristig ab." },
    { "emoji": "🚶🛍️", "bedeutung": "Vielleicht sollten wir spontan etwas einkaufen gehen." },
    { "emoji": "🎨🍷", "bedeutung": "Was, wenn wir danach eine Ausstellung besuchen?" },
    { "emoji": "🌳🚶", "bedeutung": "Ich hoffe, wir machen einen Spaziergang im Park." },
    { "emoji": "📸😅", "bedeutung": "Was, wenn sie/er ein Selfie vorschlägt?!" },
    { "emoji": "😴🚶", "bedeutung": "Ich sollte nicht so müde wirken." },
    { "emoji": "😓👕", "bedeutung": "Ob mein Outfit zu knitterig aussieht?" },
    { "emoji": "💬📱", "bedeutung": "Sollte ich noch mal anrufen und sagen, dass ich komme?" },
    { "emoji": "🤔😇", "bedeutung": "Ich hoffe, ich mache einen guten Eindruck." },
    { "emoji": "🏙️👀", "bedeutung": "Die Architektur hier ist echt beeindruckend." },
    { "emoji": "🌳🍃", "bedeutung": "Der Park sieht heute so friedlich aus." },
    { "emoji": "🏠🤔", "bedeutung": "Wer wohl in diesen schönen alten Häusern wohnt?" },
    { "emoji": "👥🚶", "bedeutung": "Warum laufen hier so viele Leute in dieselbe Richtung?" },
    { "emoji": "🐕🐾", "bedeutung": "Dieser Hund ist echt süß! Welche Rasse das wohl ist?" },
    { "emoji": "🚧🙄", "bedeutung": "Diese Baustelle ist schon wieder überall im Weg." },
    { "emoji": "🌇✨", "bedeutung": "Der Sonnenuntergang sieht zwischen den Gebäuden fantastisch aus." },
    { "emoji": "📸🏙️", "bedeutung": "Sollte ich ein Foto von dieser Aussicht machen?" },
    { "emoji": "🚶🌍", "bedeutung": "Die Straßen sind heute so belebt – was ist los?" },
    { "emoji": "🌲🍃", "bedeutung": "Es riecht so frisch hier, wie im Wald." },
    { "emoji": "🚶‍♀️🏬", "bedeutung": "Dieser Laden hat ein so auffälliges Schaufenster." },
    { "emoji": "🛤️🤔", "bedeutung": "Wo führt diese kleine Seitengasse hin?" },
    { "emoji": "👂🕊️", "bedeutung": "Ich höre überall Vogelgezwitscher – so schön!" },
    { "emoji": "🏢💡", "bedeutung": "Die Neonlichter an diesem Gebäude sind faszinierend." },
    { "emoji": "🎶🚶", "bedeutung": "Habe ich gerade Straßenmusik gehört? Woher kam das?" },
    { "emoji": "🚗🚦", "bedeutung": "Der Verkehr heute ist wirklich chaotisch." },
    { "emoji": "🏠🌺", "bedeutung": "Diese Balkone sind so hübsch mit den Blumen dekoriert." },
    { "emoji": "🛑🚶‍♂️", "bedeutung": "Ich sollte vorsichtig sein, hier fahren viele Radfahrer." },
    { "emoji": "🍂🍁", "bedeutung": "Die Blätter am Boden geben der Straße ein richtig herbstliches Gefühl." },
    { "emoji": "⛲👀", "bedeutung": "Dieser Brunnen sieht so alt und historisch aus." },
    { "emoji": "🌸🌳", "bedeutung": "Die Bäume blühen so schön, der Frühling ist da." },
    { "emoji": "👩‍🎨🎨", "bedeutung": "Ob dieser Straßenkünstler ein neues Bild malt?" },
    { "emoji": "🏗️🕰️", "bedeutung": "Wie lange dauert es wohl, bis dieses Gebäude fertig ist?" },
    { "emoji": "🍃💨", "bedeutung": "Es ist so windig hier, ich muss meinen Schal festhalten." },
    { "emoji": "🪞🏙️", "bedeutung": "Das Spiegelbild der Gebäude sieht im Glas echt cool aus." },
    { "emoji": "🛝👨‍👩‍👧‍👦", "bedeutung": "Auf dem Spielplatz herrscht so viel Leben, die Kinder wirken glücklich." },
    { "emoji": "🛤️🌅", "bedeutung": "Der Horizont sieht wie aus einem Gemälde aus." },
    { "emoji": "🐦🪶", "bedeutung": "So viele Tauben hier, die warten bestimmt auf Essen." },
    { "emoji": "🎨🧑‍🎨", "bedeutung": "Die Straßenkunst hier ist wirklich beeindruckend." },
    { "emoji": "🚶‍♂️🍔", "bedeutung": "Dieser Imbiss duftet unglaublich gut – das zieht viele Leute an." },
    { "emoji": "🚲🔔", "bedeutung": "Warum klingen überall Fahrradklingeln? Es ist so hektisch hier." },
    { "emoji": "💡🌆", "bedeutung": "Die Stadt sieht nachts so lebendig aus mit all den Lichtern." },
    { "emoji": "📖🏛️", "bedeutung": "Ob diese Bibliothek innen genauso beeindruckend ist wie außen?" },
    { "emoji": "🚶‍♀️🌸", "bedeutung": "Die Blumenbeete sind so schön gepflegt." },
    { "emoji": "🚶🌞", "bedeutung": "Die Sonne scheint so warm, es tut gut, draußen zu sein." },
    { "emoji": "🐕💩", "bedeutung": "Warum räumt die Person den Hundehaufen nicht weg?" },
    { "emoji": "🛍️🏬", "bedeutung": "Dieser neue Laden hat so ein cooles Design, da muss ich später rein." },
    { "emoji": "🛤️🚆", "bedeutung": "Ob ich von hier die Züge beobachten kann?" },
    { "emoji": "🌂💭", "bedeutung": "Zum Glück habe ich meinen Regenschirm dabei – es sieht nach Regen aus." },
    { "emoji": "🚶‍♀️🌇", "bedeutung": "Die Farben des Himmels sind so unglaublich schön." },
    { "emoji": "🚶🍃", "bedeutung": "Es ist so still hier – kaum Verkehr und nur Naturgeräusche." },
    { "emoji": "📜🏠", "bedeutung": "Ob dieses Gebäude unter Denkmalschutz steht?" },
    { "emoji": "🏛️👀", "bedeutung": "Die Säulen an diesem Gebäude sind so beeindruckend." },
    { "emoji": "🌳🧘", "bedeutung": "Dieser Park sieht perfekt aus, um etwas Yoga zu machen." },
    { "emoji": "🪶🐦", "bedeutung": "Da hinten sehe ich einen besonders farbenfrohen Vogel." },
    { "emoji": "🏗️📈", "bedeutung": "Wie schnell die Stadt wächst – hier wird überall gebaut." },
    { "emoji": "🚶‍♂️⛪", "bedeutung": "Ob die Kirche hier offen ist? Die Architektur ist wunderschön." },
    { "emoji": "🌳🏙️", "bedeutung": "Die Mischung aus Stadt und Natur gefällt mir." }
  ]
  

  export const WaitingSentences = [
    { "emoji": "⌛👥😤", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "🕰️🙄", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "👥🕒🤔", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "🙃⌛", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "😤⏳👥", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "😩🕒🛑", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "🤷‍♀️⌛", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "🕰️🙄", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "⌛😓👥", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "😑🕒👥", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "⌛👥", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "😤🕰️", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "🙄⌛", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "🕒😩", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "😅👥", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "⌛😓", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "😑🕒", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "🙃🕰️", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "😩👥", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." },
    { "emoji": "🤔⌛", "bedeutung": "Ich warte in dieser Schlange schon sehr lange." }
  ]


export const HungrySentences = [
    { "emoji": "🤔", "bedeutung": "Ein Sandwich wäre schnell gemacht." },
    { "emoji": "🙌", "bedeutung": "Sushi wäre ein Traum." },
    { "emoji": "😅", "bedeutung": "Vielleicht reicht ein Hotdog, um mich zu retten." },
    { "emoji": "🤔", "bedeutung": "Ob ich irgendwo Dumplings bekomme?" },
    { "emoji": "🤤", "bedeutung": "Eine große Schüssel Ramen bitte!" },
    { "emoji": "😌", "bedeutung": "Eiscreme wäre genau das Richtige jetzt." },
    { "emoji": "😋", "bedeutung": "Ein Wrap wäre genau richtig." },
    { "emoji": "🍴", "bedeutung": "Ein Cheeseburger wäre himmlisch." },
  ]
  
export const EvaluateQueueSentences = [
  { "emoji": "🤔🛒", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "🤷‍♂️", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "🙄🛒", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "💳🤔", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "😬💰❓", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "💸🤷", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "🤨💳", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "🛒❓", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "💰🙄", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "🤷‍♀️💵", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "🤔💰", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "🙄💳", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "😟🛒", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "😬💸", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "🤔🛒❓", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "😬💳", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "🤔👛", "bedeutung": "Soll ich wirklich hier was kaufen?" },
  { "emoji": "🤔🛒", "bedeutung": "Soll ich wirklich hier was kaufen?" },
]

  export const VerifySentences = [
    { "emoji": "😋✨", "bedeutung": "Das hat sich total gelohnt!" },
    { "emoji": "🤤👍", "bedeutung": "Das Warten war es absolut wert." },
    { "emoji": "🙄😐", "bedeutung": "Ganz okay, aber nichts Besonderes." },
    { "emoji": "😌😊", "bedeutung": "Ich bin zufrieden und fühle mich wohl." },
    { "emoji": "😅💸", "bedeutung": "Es war gut, aber dafür eindeutig zu teuer." },
    { "emoji": "😏🤔", "bedeutung": "Ich bin mir nicht sicher, ob das wirklich nötig war." },
    { "emoji": "🙃👎", "bedeutung": "Das hätte ich mir sparen können." },
    { "emoji": "🤩👏", "bedeutung": "Ich bin begeistert! Ich komme sicher wieder." },
    { "emoji": "😳😒", "bedeutung": "Das hat meine Erwartungen leider nicht erfüllt." },
    { "emoji": "😄🙌", "bedeutung": "Ich bin froh, dass ich gewartet habe!" },
    { "emoji": "😠🙄", "bedeutung": "Das war eine totale Enttäuschung." },
    { "emoji": "😌💭", "bedeutung": "Nächstes Mal plane ich das besser ein." },
    { "emoji": "🤤✨", "bedeutung": "Ich bin mehr als zufrieden – das war großartig!" },
    { "emoji": "🤔😐", "bedeutung": "Es war okay, aber nichts, was ich noch mal machen würde." },
    { "emoji": "😤👎", "bedeutung": "Das hat sich überhaupt nicht gelohnt." },
    { "emoji": "🤷‍♂️🙂", "bedeutung": "Es war ganz nett, aber nichts Außergewöhnliches." },
    { "emoji": "😍🙌", "bedeutung": "Das hat mich wirklich glücklich gemacht." },
    { "emoji": "😓💸", "bedeutung": "Zu teuer für das, was es war." },
    { "emoji": "✨🤩", "bedeutung": "Ein tolles Erlebnis, das mich überzeugt hat." },
    { "emoji": "👎😐", "bedeutung": "Ich hätte mir etwas Besseres erwartet." },
    { "emoji": "😊✨", "bedeutung": "Ich fühle mich gut und habe es genossen." },
    { "emoji": "😩🙄", "bedeutung": "Die Wartezeit hat meine Laune komplett verdorben." },
    { "emoji": "😁👏", "bedeutung": "Das war eine super Erfahrung!" },
    { "emoji": "😏😅", "bedeutung": "Es war in Ordnung, aber nicht mein Highlight." },
    { "emoji": "😎✨", "bedeutung": "Das war cool, ich würde es wiederholen." },
    { "emoji": "😤🤷", "bedeutung": "Ich habe mehr erwartet und wurde enttäuscht." },
    { "emoji": "😊💭", "bedeutung": "Das hat mich richtig zufrieden gemacht." },
    { "emoji": "😔👎", "bedeutung": "Das war leider gar nichts für mich." },
    { "emoji": "😁✨", "bedeutung": "Ein Erlebnis, das ich in Erinnerung behalten werde!" },
    { "emoji": "🤷‍♂️🙂", "bedeutung": "Es war okay, aber es hat mich nicht umgehauen." }
  ]
  